# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
    ]
