# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
